= Sans Comic Viewer

Sans is a simple little comic viewer that supports comic archives.
Currently only `.CBZ` (ZIP format) comic archives are supported.

I wrote this as practice with Windows Presentation Foundation and the Model-View-ViewModel architecture.
As such, this program is not optimized for being a good comic viewer.
It works pretty well nonetheless.

To-do:

* Go -> Go To Page
* Help -> About
* Other comic archive formats

== Copyright and License Notice

Copyright (C) 2020 Megan Ruggiero.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
